feat(community): 로그인/회원가입 페이지 추가
kgu-developers/aics-client pull request #27
Opened 2024-11-18 10:05 UTC by m2na7

## Summary

> #24 

로그인&회원가입(auth) 페이지(/signin , /singup) 구현

## Tasks

- auth 페이지에서 사용하는 AuthInput, AuthButton 컴포넌트를 추가했습니다.
  - 해당 컴포넌트는 추후 DS로 변경 가능
- 로그인, 회원가입 폼을 추가했습니다.
- 로그인, 회원가입 폼 관련 스키마를 추가했습니다. (schemas폴더 생성)

## To Reviewer

로그인/회원가입 폼 컴포넌트를 각각 구현했어요.

`Form`컴포넌트, `useFormHandler`커스텀 훅으로 관련 로직을 분리해서 구현하는 방법도 있고, 실제로 구현해보았는데 구조가 지나치게 복잡해진다고 생각했어요.

인증 관련 폼은 로그인/회원가입에만 사용되고, 공통 로직을 분리하는 과정에서 오버엔지니어링이 된다고 판단했고, 각각의 컴포넌트 (`SignInForm`, `SignUpForm`)로 구현했어요.
관련해서 의견주시면 반영해보도록 하겠습니다 😃

## Screenshot

<img width="1513" alt="스크린샷 2024-11-18 오후 7 02 29" src="https://github.com/user-attachments/assets/cec3def1-267a-468c-af05-b23c03c0c4f6">

<img width="1513" alt="스크린샷 2024-11-18 오후 7 02 58" src="https://github.com/user-attachments/assets/60386097-2843-4228-b608-6ec47bf35d2a">

<img width="1513" alt="스크린샷 2024-11-18 오후 7 03 43" src="https://github.com/user-attachments/assets/545c9cb0-8d38-4d34-9e84-3c2f472d791a">

2024-11-18 10:38 UTC, SunwooJaeho commented on apps/community/src/app/(auth)/signin/page.tsx
> +      </div>
태그 간 간격이 있었으면 가독성이 더 좋아질 것 같아요!

2024-11-18 10:38 UTC, SunwooJaeho commented on apps/community/src/components/auth-input.css.ts
> +  borderRadius: 8,
토큰 사용해도 될 것 같아요!

2024-11-18 10:38 UTC, SunwooJaeho commented on apps/community/src/app/(auth)/signup/page.tsx
> +        <h1 className={styles.title}>회원가입</h1>
해당 부분은 컴포넌트화가 가능해보입니다!

2024-11-18 10:38 UTC, SunwooJaeho commented on apps/community/src/components/sign-up-form.tsx
> +  const [studentId, password, confirmPassword, name, email, phone] = useWatch({
useWatch 대신 formState와 isValid를 이용하는 건 어떨까요?

2024-11-18 12:09 UTC, m2na7 commented on apps/community/src/app/(auth)/signup/page.tsx
> +        <h1 className={styles.title}>회원가입</h1>
공통으로 사용되는 부분을 AuthHeader, AuthFooter 컴포넌트로 분리했습니다 !

2024-11-19 10:46 UTC, gwansikk commented
> auth 페이지에서 사용하는 AuthInput, AuthButton 컴포넌트를 추가했습니다.
해당 컴포넌트는 추후 DS로 변경 가능

AuthInput은 직접 DS에 컴포넌트로 추가하여 해당 PR에 포함해도 좋을 거 같습니다. 어때요?

2024-11-19 11:05 UTC, gwansikk requested changes
빠르게 작업하셨네요 👍👍 몇 가지 제안합니다.

- app/(auth)/components

해당 폴더에서 auth에 관련된 '공용' 컴포넌트가 선언되어 있는데요. 여기서 sign-in-form이나 sign-upform 등 signin, signup에서 사용되는 전용 컴포넌트가 해당 폴더에 포함하신 이유가 궁금해요.

저는 각각 페이지 폴더에 components에 선언되어야 한다고 생각합니다.

2024-11-19 11:05 UTC, gwansikk commented on apps/community/src/app/(auth)/signin/page.css.ts
section 스타일은 signin, signup에 동일한 스타일, 컴포넌트로 사용하고 있어요. 이를 auth/layout으로 잡는 건 어떤가요?

2024-11-19 11:05 UTC, gwansikk commented on apps/community/src/components/auth-button.css.ts
👍👍 참고하여 DS에 반영하도록 할게요

2024-11-19 11:05 UTC, gwansikk commented on apps/community/src/components/auth-input.tsx
> +}
```suggestion
function AuthInput({ type, ...props }: InputProps) {
  return (
    <input
      className={styles.input}
      type={type}
      {...props}
    />
  );
}
```

placeholder를 rest에 넣지 않고 따로 빼서 할당한 이유가 있나요?

2024-11-19 11:05 UTC, gwansikk commented on apps/community/src/components/sign-in-form.tsx
> +  const isFormValid = studentId && password;
```suggestion
  const {
    register,
    handleSubmit,
    control,
    formState: { errors },
  } = useForm<z.infer<typeof signInFormSchema>>({
    resolver: zodResolver(signInFormSchema),
    defaultValues,
  });
  const [studentId, password] = useWatch({
    control,
    name: ['studentId', 'password'],
  });

  const onSubmit = (data: z.infer<typeof signInFormSchema>) => {
    console.log(data);
  };
  const isFormValid = studentId && password;
```

훅은 상단에 선언되어 모여있도록 하면 훅과 이벤트를 구분하고 가독성 있게 구조적으로 볼 수 있어요

2024-11-19 11:05 UTC, gwansikk commented on apps/community/src/schemas/sign-up-form-schema.ts
> +const defaultValues = {
해당 변수명은 명확하지 않고 export 될 경우 구분하기 어렵다고 생각해요. 스키마가 많아질 경우 import 할 때 자동완성에서 너무나 많이 나타날게 우려됩니다.

2024-11-19 11:05 UTC, gwansikk commented on apps/community/src/components/sign-up-form.tsx
> +          id="name"
id가 하드 코딩 되어 있어 유지보수하기 어렵거나, 사이드 이펙트가 발생될 거 같아요 (e.g. name을 userName으로 변경한다면? 모두 잘 변경할 수 있을까)

2024-11-19 11:05 UTC, gwansikk commented on apps/community/src/schemas/sign-in-form-schema.ts
> +});
스키마의 규모가 작거나 다양하게 나타나지 않는다면 저는 같은 파일(모듈 스코프)에 넣는 것을 지향해요. 같은 파일에 선언되어 있으면 여러 파일을 살펴보지 않고도 빠르게 수정하고 확인할 수 있는 응집도가 생기기 때문인데요. 어떤가요

2024-11-21 16:54 UTC, gwansikk commented
@m2na7 브랜치 최신으로 업데이트 했습니다 pull 당겨주시고, 리뷰한거 피드백 해주세요

2024-11-21 18:27 UTC, m2na7 commented on apps/community/src/components/auth-input.tsx
> +}
placeholder가 필수요소라고 생각하고 구현했는데, 생각해보니 필요없는 부분이었어요.
DS에 input 컴포넌트 추가하면서 제거했습니다

2024-11-21 18:28 UTC, m2na7 commented on apps/community/src/schemas/sign-up-form-schema.ts
> +const defaultValues = {
스키마를 같은 파일에 넣어줌으로써 defaultValues를 export할 필요가 없어졌기에 해당 변수명은 그대로 유지했습니다 !

2024-11-21 18:29 UTC, m2na7 commented on apps/community/src/components/sign-up-form.tsx
> +          id="name"
React Hook Form의 `register`를 사용함으로써 하드코딩된 id는 제거했습니다 !

2024-11-21 18:30 UTC, m2na7 commented on apps/community/src/schemas/sign-in-form-schema.ts
> +});
저도 동의합니다 😃

2024-11-21 18:32 UTC, m2na7 commented
input컴포넌트는 DS에 반영했고, 전체 파일 폴더구조(src/component) 변경했습니다 !
@gwansikk @SunwooJaeho

2024-11-21 18:41 UTC, gwansikk requested changes

2024-11-21 18:41 UTC, gwansikk commented on packages/design-system/src/components/input/input.tsx
> +  value?: string;
```suggestion
```

2024-11-21 18:41 UTC, gwansikk commented on packages/design-system/src/components/input/input.tsx
> +      <input value={value} className={styles.input()} {...props} />
```suggestion
      <input className={styles.input()} {...props} />
```

2024-11-21 18:41 UTC, gwansikk commented on apps/community/src/app/(auth)/layout.tsx
Layout은 nesting-layouts를 사용하여 children으로 내려주는 방법으로 사용해주세요

ref: https://nextjs.org/docs/app/building-your-application/routing/layouts-and-templates#nesting-layouts

2024-11-21 18:46 UTC, gwansikk commented on packages/design-system/src/components/input/input.tsx
> +  className?: string;
```suggestion
```

2024-11-21 20:14 UTC, gwansikk approved these changes
LGTM

2024-11-21 20:18 UTC, merged