feat(community): 공지사항 페이지
kgu-developers/aics-client pull request #37
Opened 2024-11-28 16:50 UTC by SunwooJaeho

## Summary

> issue #26 

공지사항 페이지 퍼블리싱을 하였어요.

## Tasks

- init lucide icons
- 공지사항 페이지 퍼블리싱
    - 페이지네이션을 적용하였어요. 

## To Reviewer
디자인적으로 수정사항이 필요하거나 아이디어가 떠오른다면 적극적으로 말해주세요!

## Screenshot

(기존 page의 size는 10이나, 촬영 편의성을 위해 5로 조정하였어요.)

![DemoCreatorRec_2024-11-2901-43-11-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/3168e34a-cd23-4525-a30d-f33e586f146d)

2024-11-28 17:06 UTC, SunwooJaeho commented on apps/community/src/components/board/page-controller.tsx
> +
이해가 다소 안될 수 있을 것 같아 JSDoc을 추가했어요. 불필요하다면 삭제할게요!

2024-11-29 11:39 UTC, gwansikk requested changes

2024-11-29 11:39 UTC, gwansikk commented on apps/community/src/app/board/notice/page.tsx
> +  }, [fetchBoards]);
패칭 방법을 useEffect를 사용한 이유가 있을까요? 서버 컴포넌트로 하면 데이터를 바로 내려서 선언적으로 사용할 수 있어요.

ref: https://nextjs.org/docs/app/building-your-application/data-fetching/fetching

2024-11-29 11:39 UTC, gwansikk commented on apps/community/src/app/board/notice/page.tsx
> +  const [totalElements, setTotalElements] = useState(0);
쿼리 파라미터를 사용하지 않고 상태를 사용한 이유가 있을까요?
해당 구조는 URL로 공유할 경우 기본값이 적용되어 페이지 공유가 어려울 거 같아요 (지금은 URL로 공유할 수 없는 구조)
(e.g. `board/notice?page=10`의 URL을 공유할 경우 기본값으로 되어 공유가 안될 거 같아요)

2024-11-29 11:39 UTC, gwansikk commented on apps/community/src/app/board/notice/page.tsx
제 개인적인 생각으로 공지사항 페이지는 공유가 될 수 있다고 생각해요 (e.g. `?page=10`)
그렇다면 쿼리 파라미터를 사용해야 하고 지금 구현된 구조가 많이 변경될 거라 생각해요.

2024-11-29 11:39 UTC, gwansikk commented on apps/community/src/app/board/notice/remote.ts
> +}
해당 타입은 공용 타입으로 빼도 될거 같아요 (서버에서 내려주는 페이지네이션 공통 스키마라고 생각해요)

2024-11-29 11:39 UTC, gwansikk commented on apps/community/src/app/board/notice/remote.ts
> +  const url = `${MOCK_END_POINT.BOARD}?page=${page}&size=${size}&keyword=${encodeURIComponent(keyword)}&category=${encodeURIComponent(category)}`;
ref: https://developer.mozilla.org/ko/docs/Web/API/URLSearchParams

2024-11-29 11:39 UTC, gwansikk commented on apps/community/src/components/board/list.css.ts
> +  },
미디어 쿼리는 디자인시스템의 `screen.xl()`로 사용할 수 있어요

2024-11-29 11:39 UTC, gwansikk commented on apps/community/src/components/board/list.tsx
명명 컨벤션을 지키고 컴포넌트 이름과 동일하게 해주세요. `board-list.tsx`

2024-11-29 11:39 UTC, gwansikk commented on apps/community/src/components/board/list.tsx
> +          {board.hasAttachment && <Paperclip color="grey" size={'0.75rem'} />}
사이즈 토큰을 만드는 건 어떨까 생각이 들어요. 다른 분들 의견 부탁드려요

2024-11-29 11:39 UTC, gwansikk commented on apps/community/src/components/board/page-controller.tsx
쿼리 파라미터를 사용하면 해당 컨트롤러 로직도 변경될 거라고 생각해요

2024-11-29 15:55 UTC, SunwooJaeho commented on apps/community/src/components/board/list.tsx
> +          {board.hasAttachment && <Paperclip color="grey" size={'0.75rem'} />}
사이즈 토큰은 크기 단위가 작은 것부터 큰 것까지 매우 많아질 것 같은데 괜찮을까요?

2024-11-29 15:59 UTC, SunwooJaeho commented on apps/community/src/components/board/board-list.tsx
totalPage를 따로 불러 올 방법이 마땅치 않은 것 같아 Pagination 컴포넌트를 BoardList 내부에서 관리했습니다! 좋은 방법이 있다면 의견 제시해주세요!👍

2024-11-29 18:02 UTC, gwansikk requested changes

2024-11-29 18:02 UTC, gwansikk commented on apps/community/src/app/board/notice/page.tsx
> +  const size = 10;
모듈 스코프에 상수로 선언해도 좋을 거 같아요 (리액트에서 핸들링하지 않는 데이터)

2024-11-29 18:02 UTC, gwansikk commented on apps/community/src/components/board/board-list.css.ts
> +});
```suggestion
const author = style([{
  width: '0%',
  visibility: 'hidden'
},
screen.xl({
    visibility: 'visible',
    width: 'auto',
  })
]);
```

배열로 스타일을 주입할 수 있어요 (이런 방법이 있는지 알려주는거에요)

2024-11-29 18:02 UTC, gwansikk commented on apps/community/src/components/board/pagination.tsx
> +  const [start, setStart] = useState(1);
변수명이 명확하지 않아요, 해당 상태는 StartPage를 저장하고 있지도 않아요 (상태가 변경됨)

2024-11-29 18:02 UTC, gwansikk commented on apps/community/src/components/board/pagination.tsx
> +  }, [currentPage, pageCount, start]);
`useEffect`를 사용하지 않고 핸들러에서 업데이트할때 검증을 추가하는 건 어떨까요

2024-11-29 18:02 UTC, gwansikk commented on apps/community/src/components/board/search-bar.tsx
> +      />
DS의 input을 사용해도 좋을 거 같아요 (가능하다면)

2024-11-29 18:02 UTC, gwansikk commented on apps/community/src/components/board/search-bar.tsx
> +    if (e.key === 'Enter') handleSearch(keyword);
```suggestion
    if (e.key === 'Enter') {
      handleSearch(keyword);
    }
```

2024-11-29 18:02 UTC, gwansikk commented on apps/community/src/types/board.ts
> +}
해당 타입은 페이지네이션 API라면 공통으로 내려오는 스키마이기 떄문에 공통 type으로 선언하여 가져오면 좋을 거 같아요.
그리고 실제 데이터는 아래와 같이 내려와요. 참고하여 BaseReponse와 조합하여 정의해주세요.

```typescript
data: {
  contents: T[];
  pagable: {
    page: number;
    size: number;
    totalPage: number;
    totalElements: number;
    isEnd: boolean;
  }
}
```

2024-11-29 18:02 UTC, gwansikk commented on apps/community/src/components/board/board-list.tsx
> +async function BoardList({ data }: { data: Board[] }) {
해당 컴포넌트는 추상화 레벨, 결합도가 높다는 것이 걱정이네요. 일단 현재 상태에서는 DS의 리스트에서 사용하기 어렵다고 판단되어 이와 같이 구현한 것으로 보여지는데요. 일단 넘어가고 나중에 DS 리스트를 활용하는 것이 좋아보여요.

다른 분들 좋은 아이디어가 있다면 피드백주세요

2024-11-29 18:12 UTC, gwansikk commented on apps/community/src/components/board/list.tsx
> +          {board.hasAttachment && <Paperclip color="grey" size={'0.75rem'} />}
제가 의도한건 아이콘마다 사용하는 크기를 표준화 할 필요가 있다예요 size를 토큰으로 모두 선언하기 어렵겠지만, 아이콘의 크기를 표준화 하기 위해 XS, SM, MD, XL와 같은 토큰이 필요하다는 의도였어요 (아이콘 크기 통일을 위해)

2024-12-01 11:00 UTC, SunwooJaeho commented on apps/community/src/components/board/list.tsx
> +          {board.hasAttachment && <Paperclip color="grey" size={'0.75rem'} />}
사이즈 토큰은 작업을 어느 정도 진행 한 후  xs / sm ..등에 적합한 크기를 같이 고민해보는 것이 좋을 듯 합니다!

2024-12-01 11:17 UTC, SunwooJaeho commented on apps/community/src/components/board/pagination.tsx
> +  }, [currentPage, pageCount, start]);
좋은 생각인 것 같습니다! 수정해서 반영하도록 할게요👍

2024-12-01 11:19 UTC, SunwooJaeho commented on apps/community/src/components/board/pagination.tsx
> +  const [start, setStart] = useState(1);
변수명을 listStart로 수정하였어요!

2024-12-01 11:56 UTC, SunwooJaeho commented on apps/community/src/components/board/search-bar.tsx
> +      />
적용 완료하였어요!

2024-12-01 13:08 UTC, gwansikk commented on apps/community/src/components/board/list.tsx
> +          {board.hasAttachment && <Paperclip color="grey" size={'0.75rem'} />}
그렇다면 아이콘 크기가 일관적이지 않고 코드가 쌓이게 될텐데 괜찮을까요 (제가 원하는건 아이콘에 대해 일관적인 크기를 임시적으로 두는 것을 말하는거에요)

지금처럼 하드코딩 된다면 나중에 바꾸기도 어렵다고 생각해요

2024-12-01 13:11 UTC, SunwooJaeho commented on apps/community/src/components/board/list.tsx
> +          {board.hasAttachment && <Paperclip color="grey" size={'0.75rem'} />}
그렇다면 1rem을 md 값으로 두고 0.25rem 단위로 자르는 것은 어떨까요?

2024-12-01 13:12 UTC, gwansikk commented on apps/community/src/components/board/list.tsx
> +          {board.hasAttachment && <Paperclip color="grey" size={'0.75rem'} />}
icon size 토큰을 따로 만들어도 좋을거 같아요

> 그렇다면 1rem을 md 값으로 두고 0.25rem 단위로 자르는 것은 어떨까요?

일단 뭐든 좋습니다. 의도한대로 추가해주세요

2024-12-01 13:46 UTC, m2na7 commented on apps/community/src/app/board/notice/remote.ts
> +import type { BoardResponse } from '~/types/board';
```suggestion
import { http } from '~/utils/http';
import { MOCK_END_POINT } from '~/constants/api';
import type { BoardResponse } from '~/types/board';
```
띄어쓴 이유가 있나요 ?

2024-12-01 13:46 UTC, m2na7 commented on apps/community/src/components/board/list.tsx
> +          {board.hasAttachment && <Paperclip color="grey" size={'0.75rem'} />}
> icon size 토큰을 따로 만들어도 좋을거 같아요

해당 의견에 동의합니다 ~

2024-12-01 13:46 UTC, m2na7 commented on apps/community/src/components/board/board-list.css.ts
> +  gap: '1rem',
`gap` 속성들은 `Spacing` 토큰에서 값을 가져오도록 하는건 어떨까요 ?

2024-12-01 14:29 UTC, SunwooJaeho commented on apps/community/src/app/board/notice/remote.ts
> +import type { BoardResponse } from '~/types/board';
가독성을 위해 띄어썼습니다!

2024-12-01 14:29 UTC, SunwooJaeho commented on apps/community/src/components/board/board-list.css.ts
> +  gap: '1rem',
수정하여 올릴게요!

2024-12-02 07:45 UTC, m2na7 approved these changes

2024-12-02 13:00 UTC, gwansikk approved these changes
- 타입 선언 피드백 확인해주시고 정리 부탁드려요
- ds의 size token을 추가하고 사용하지 않는 것으로 보여요, 사용하지 않는다면 삭제해주세요 (다음 버전에서 아이콘 크기를 위한 사이드 토큰을 추가해볼게요)

2024-12-02 13:00 UTC, gwansikk commented on apps/community/src/app/board/notice/remote.ts
> +  return await http.get<PaginationResponse>(url);
```suggestion
  return http.get<PaginationResponse>(`${MOCK_END_POINT.BOARD}?${params.toString()}`);
```

2024-12-02 13:00 UTC, gwansikk commented on apps/community/src/app/board/notice/remote.ts
> +async function getBoards(
```suggestion
function getBoards(
```

2024-12-02 13:00 UTC, gwansikk commented on apps/community/src/app/board/notice/remote.ts
> +  const url = `${MOCK_END_POINT.BOARD}?${params.toString()}`;
```suggestion
```

2024-12-02 13:00 UTC, gwansikk commented on apps/community/src/types/api.ts
> +export type { BaseResponse, PaginationResponse };
```suggestion
type BaseResponse<T> = {
  data: T;
};

type PaginationResponse<T> = BaseResponse<{
  contents: T[];
  pageable: Pageable;
}>;

interface Pageable {
  page: number;
  size: number;
  totalPage: number;
  totalElements: number;
  isEnd: boolean;
}

export type { BaseResponse, PaginationResponse, Pageable };
```

2024-12-02 13:00 UTC, gwansikk commented on apps/community/src/types/api.ts
> +import type { Board, Pagable } from './board';
```suggestion
```

2024-12-02 13:00 UTC, gwansikk commented on apps/community/src/types/board.ts
> +}
Board 타입은 board/notice/remote.ts 로 옮겨주시고, 아래에 선언된 Pagable 타입은 정리해주세요

2024-12-02 13:00 UTC, gwansikk commented on apps/community/src/components/board/search-bar.tsx
> +    }
params에 선언되는 키가 하드코딩 되어 있어요. 모듈 스코프에 선언해주세요 (`page`, `keyword`)

2024-12-02 17:21 UTC, merged