feat(community): 마이 페이지 추가
kgu-developers/aics-client pull request #38
Opened 2024-12-02 15:38 UTC by m2na7

## Summary

> #35

마이페이지(회원)를 추가했습니다.

## Tasks

- 마이페이지 퍼블리싱
- boxShadow 토큰 추가
- DS button 컴포넌트내 outline 색상 추가

## Screenshot
- DS button 컴포넌트내 outline 색상 추가
<img width="634" alt="스크린샷 2024-12-05 오후 4 50 48" src="https://github.com/user-attachments/assets/e0f56945-e7ed-485e-9bfb-fbcddbfe8815">

- 마이페이지
<img width="1290" alt="스크린샷 2024-12-06 오후 6 22 39" src="https://github.com/user-attachments/assets/b098cba9-9e33-4476-a82f-99ef1f61c86c">

전화번호, 이메일 변경 기능을 추가했습니다.

## To Reviewer

컴파운드 패턴을 적용했는데 해당 부분에 대한 피드백 부탁드립니다.

2024-12-02 17:32 UTC, SunwooJaeho commented on apps/community/src/components/users/user-card.css.ts
> +  boxShadow: '0 1px 3px 0 rgb(0 0 0 / 0.1)',
box-shadow를 토큰화 하는 건 어떨까요? 다른 분들의 의견이 궁금합니다!

2024-12-02 17:33 UTC, SunwooJaeho approved these changes

2024-12-02 17:51 UTC, SunwooJaeho approved these changes
LGTM🙋‍♂️

2024-12-03 01:20 UTC, m2na7 commented on apps/community/src/components/users/user-card.css.ts
> +  boxShadow: '0 1px 3px 0 rgb(0 0 0 / 0.1)',
좋은생각같아요 ~ 다른 분들도 동의하시면 이번 PR에 반영해서 올리겠습니다 !
@gwansikk @wontory

2024-12-03 07:02 UTC, gwansikk commented on apps/community/src/components/users/user-card.css.ts
> +  boxShadow: '0 1px 3px 0 rgb(0 0 0 / 0.1)',
동의합니다. 토큰화 된다면 더욱 편리하게 사용할 수 있을거 같아요

2024-12-03 07:54 UTC, gwansikk commented
기존 cs-home 프로젝트에서는 마이페이지에 비밀번호 변경 및 활동내역도 확인할 수 있었어요. 관련하여 추가하는건 어떨까요

| 회원정보 | 활동내역 |
| --- | --- |
| <img width="1020" alt="image" src="https://github.com/user-attachments/assets/770f4bd4-2e23-434f-adef-1e340f9b14b3">| <img width="1022" alt="image" src="https://github.com/user-attachments/assets/2f69f428-d8ac-4859-97d7-cddb3531af45">|

2024-12-03 08:04 UTC, m2na7 commented on apps/community/src/components/users/user-card.css.ts
> +  boxShadow: '0 1px 3px 0 rgb(0 0 0 / 0.1)',
해당 부분 추가했습니다 ~

2024-12-03 08:05 UTC, gwansikk requested changes
```ts
USERS: `${MOCK_BASE_URL}/users`,
```

URL을 `users`를 사용한 이유가 궁금합니다. 해당 페이지는 '마이 페이지'인데 users라고 지정한 이유가 있나요?

2024-12-03 08:05 UTC, gwansikk commented on apps/community/src/components/users/user-list.tsx
> +function UserList({ title, children }: Props) {
`UserList`라는 이름은 명확하지 않다고 생각해요. 실제로는 유저 정보를 하나씩 표시해주고 있는데 UserList라고 명명하나 이유가 있나요?

2024-12-03 08:05 UTC, gwansikk commented on apps/community/src/components/users/user-list.tsx
> +export { UserList };
```tsx
<UserList key={detail.title} title={detail.title}>
  <UserList.Row>{detail.value}</UserList.Row>
</UserList>
```

컴파운드 패턴을 사용하신 이유가 궁금합니다. 실제 사용할때 위와 같이 이터레이션을 하고 있는데 Row를 여러 개 사용할 유즈-케이스가 있나요?

2024-12-03 08:12 UTC, m2na7 commented on apps/community/src/components/users/user-list.tsx
> +export { UserList };
초기 설계할 때 여러 Row를 가지는 리스트가 존재했어요.
이후에 변경되었고 패턴을 수정하지 않고 계속 사용했네요. 수정하겠습니다 ~!

2024-12-03 08:17 UTC, m2na7 commented on apps/community/src/components/users/user-list.tsx
> +function UserList({ title, children }: Props) {
UserInfoField라는 이름으로 수정하여 역할을 명확히 했습니다. 좋은 의견 감사합니다 !

2024-12-03 08:26 UTC, m2na7 commented
> ```ts
> USERS: `${MOCK_BASE_URL}/users`,
> ```
> 
> URL을 `users`를 사용한 이유가 궁금합니다. 해당 페이지는 '마이 페이지'인데 users라고 지정한 이유가 있나요?

처음에는 my보다는 users로 네이밍하는게 확장성 측면에서 더 자연스럽다고 판단했는데, users는 마이페이지 보다는 회원관리(admin)쪽에 더가까운 것 같네요. my로 수정하겠습니다 !

2024-12-03 10:21 UTC, gwansikk commented on apps/community/src/app/my/page.tsx
> +  console.log(data);
```suggestion
```

2024-12-03 10:26 UTC, gwansikk approved these changes
LGTM

2024-12-03 10:26 UTC, gwansikk commented on apps/community/src/components/my/my-info-field.tsx
> +function MyInfoField({ title, value }: Props) {
해당 컴포넌트가 단독으로 사용되는 유즈-케이스가 없다면 `MyInfoCard`에 컴파운드 패턴으로 묶어도 좋을거 같아요

2024-12-04 13:55 UTC, m2na7 commented
@SunwooJaeho @gwansikk @wontory 
이메일, 전화번호 변경기능 추가했습니다. 구조가 많이 바뀌었으니 확인 부탁드려요.
피드백은 환영입니다 !
비밀번호 변경기능은 해당 PR이 merge되면 다른 페이지(다른 PR)로 구현할 예정입니다.

2024-12-04 14:53 UTC, SunwooJaeho requested changes

2024-12-04 14:53 UTC, SunwooJaeho commented on apps/community/src/components/my/my-info-card.css.ts
> +    display: 'grid',
해당 부분은 토큰 값으로 변경이 가능해보여요!

2024-12-04 14:53 UTC, SunwooJaeho commented on apps/community/src/components/my/my-info-card.tsx
> +  };
```suggestion
 const handleEditToggle = () => setIsEditing((prev) => !prev);
```

2024-12-04 14:53 UTC, SunwooJaeho commented on apps/community/src/components/my/my-info-card.tsx
> +        </Button>
설정보다는 변경이란 단어가 더 적절하다고 생각해요 !

2024-12-04 14:53 UTC, SunwooJaeho commented on apps/community/src/app/my/page.tsx
> +      />
해당 부분은 details와 editableDetails를 분리하여 관리하는 것이 좋다고 생각이 드는데, 다른 분들의 의견이 궁금합니다!

2024-12-04 15:00 UTC, SunwooJaeho commented on apps/community/src/components/my/my-info-card.css.ts
> +    gridTemplateColumns: 'repeat(2, 1fr)',
grid.cols로 토큰화가 가능하다고 생각하는데, 다른 분들의 의견이 궁금해요!

2024-12-04 15:14 UTC, gwansikk commented on apps/community/src/components/my/my-info-card.css.ts
> +    display: 'grid',
display 속성 처럼 값이 복잡하지 않거나 선언적이면 토큰을 사용하지 않아도 된다고 생각해요 

토큰은 어떤 표준화, 일괄 적용 및 변경의 의미를 가지고 있어요. 이 외로 선언적으로 의미가 명확하다면 괜찮다고 생각합니다

2024-12-05 05:43 UTC, m2na7 commented on apps/community/src/app/my/page.tsx
> +      />
```suggestion
      <MyInfoCard
        userDetails={userDetails}
      />
      <MyInfoEditalbeCard
        userEditableDetails={userEditableDetails}
      />
```
이런 방식으로 컴포넌트를 분리하는게 좋아보인다는건가요 ??

2024-12-05 06:28 UTC, SunwooJaeho commented on apps/community/src/app/my/page.tsx
> +      />
제 개인적인 생각으로는 MyInfoCardList로 감싸는 것이 아니라 해당 코드를 그대로 드러내는 것이 낫다고 생각이 됩니다!

```
     <MyInfoCard title="내 프로필" layout="default">
        {userDetails.map((detail) => (
          <MyInfoCard.Field
            key={detail.title}
            title={detail.title}
            value={detail.value}
          />
        ))}
      </MyInfoCard>

      <MyInfoCard title="기본 정보" layout="singleColumn">
        {userEditableDetails.map((detail) => (
          <MyInfoCard.EditableField
            key={detail.title}
            title={detail.title}
            value={detail.value}
            onSave={(value) => handleSave(detail.title, value)}
          />
        ))}
      </MyInfoCard>
```

2024-12-05 07:49 UTC, m2na7 commented on apps/community/src/app/my/page.tsx
> +      />
MyPage는 async/await를 포함하는 서버 컴포넌트이고, MyInfoCardList컴포넌트는 상태관리와 이벤트 핸들링을 포함한 클라이언트 컴포넌트라서 분리를 해줬습니다.
말씀하신 방법대로 코드를 드러내는건 무리라고 생각하고, 다른 접근방법이 있다면 말씀해주세요 !!

2024-12-05 07:55 UTC, m2na7 commented on apps/community/src/components/my/my-info-card.css.ts
> +    gridTemplateColumns: 'repeat(2, 1fr)',
저는 필요 이상의 토큰화라고 생각해요

2024-12-05 11:29 UTC, SunwooJaeho commented on apps/community/src/app/my/page.tsx
> +      />
제가 놓친 부분이 있었네요😂 그럼 일단 넘어가는 걸로 할까요?

2024-12-05 11:30 UTC, SunwooJaeho approved these changes
LGTM👍

2024-12-05 13:17 UTC, gwansikk commented on apps/community/src/components/my/my-info-card.css.ts
> +    gridTemplateColumns: 'repeat(2, 1fr)',
- 저는 토큰화하면 활용성이 좋다고 생각해요 (Tailwind CSS와 같이 선언적으로 사용)
- css-in-js 형식으로 스타일 파일 외에서 스타일 주입이 가능해요

2024-12-05 13:17 UTC, gwansikk commented on packages/design-system/src/components/button/button.css.ts
👍👍👍

2024-12-05 13:17 UTC, gwansikk commented on apps/community/src/components/my/my-info-card.tsx
> +            />
EditMode에 따라 Input이 없어졌다 생겼다 하는 것은 접근성, 사용자 경험에 안좋다고 생각해요. input의 disabled 속성을 사용해서 입력을 제어하는 건 어떤가요

2024-12-05 13:17 UTC, gwansikk commented on apps/community/src/components/my/my-info-card-list.tsx
> +'use client';
API Call 때문에 미리 클라이언트 컴포넌트로 정의한건가요?

2024-12-05 13:17 UTC, gwansikk commented on apps/community/src/components/my/my-info-card.tsx
> +            }}
해당 onClick은 콜백으로 넘기고, handleEditToggle는 선언하여 사용하는데 이유가 있을까요? 해당 onClick은 왜 콜백으로 구현하게 되었나요

2024-12-06 09:21 UTC, m2na7 commented on apps/community/src/components/my/my-info-card.tsx
> +            }}
재사용되지 않고, 간단한 로직이라 생각하여 콜백으로 넘겨 구현했어요.
코드의 일관성과 가독성을 위해 선언적으로 사용하는게 더 좋아보이네요 수정했습니다 !

2024-12-06 09:24 UTC, m2na7 commented on apps/community/src/components/my/my-info-card.tsx
> +            />
좋은 생각입니다 !
사용자의 시각적인 피드백을 위해서, 추가적으로 DS내 input컴포넌트에 focus속성을 추가했습니다

2024-12-06 09:51 UTC, m2na7 commented on apps/community/src/components/my/my-info-card-list.tsx
> +'use client';
맞아요. 추가적으로 클라이언트 컴포넌트로 선언해주지 않으면 오류가 발생해서 해당 방식으로 구현했어요

2024-12-08 09:38 UTC, gwansikk requested changes

2024-12-08 09:38 UTC, gwansikk commented on apps/community/src/app/my/page.tsx
> +      />
```tsx
      <MyInfoCardList
        userDetails={userDetails}
        userEditableDetails={userEditableDetails}
      />
```
`userDetails`나 `userEditableDetails`는 동일한 타입(`{ title: string; value: number | string; }`)인데요. 이를 Props로 나누지 말고 data로 넘겨서 각각 렌더링하는 방법으로 하면 더 구분감있고 이해하기 쉬운 구조라고 생각해요.

지금 처럼 props로 구분하여 한 번에 받고 한 컴포넌트로 렌더링하는 특별한 이유가 있나요?

2024-12-08 13:29 UTC, m2na7 commented on apps/community/src/app/my/page.tsx
> +      />
>data로 넘겨서 각각 렌더링하는 방법으로 하면 더 구분감있고 이해하기 쉬운 구조라고 생각해요.

해당 의견에 동의합니다 !
기존 MyInfoCardList를 두 컴포넌트로 분리하여 수정했습니다.

```ts
      <MyInfoProfileCard data={userDetails} />
      <MyInfoEditableProfileCard data={userEditableDetails} />
```

2024-12-08 13:52 UTC, gwansikk approved these changes
수고하셨습니다~

2024-12-08 13:54 UTC, merged