chore: react19 업데이트
kgu-developers/aics-client pull request #44
Opened 2024-12-06 07:27 UTC by SunwooJaeho

## Summary

> resolved #43 

React의 버전을 stable 버전으로 최신화했어요.

## Tasks

- [X] React stable 버전(19.0.0)으로 최신화 (admin, community)
- [X] types/react 19.0.0 최신화
- [X] types/react-dom 19.0.1 최신화
- [X] code-owner 팀으로 변경

## To Reviewer

확인 후 변경 사항에 문제가 있는 것 같다면 즉시 말씀해주세요!

2024-12-06 07:44 UTC, devwontory approved these changes
LGTM

2024-12-06 07:44 UTC, wontory commented
Next.js 15 버전도 stable로 올려주세요!

2024-12-06 16:28 UTC, gwansikk requested changes
- https://github.com/kgu-developers/aics-client/pull/44#issuecomment-2522394681

2024-12-08 09:31 UTC, gwansikk approved these changes
LGTM

2024-12-08 09:53 UTC, merged