feat(community): 공지사항 상세글 페이지
kgu-developers/aics-client pull request #45
Opened 2024-12-07 18:39 UTC by SunwooJaeho

## Summary

> resolved #40 

공지사항 상세글 페이지 퍼블리싱을 했어요.

## Tasks

- 공지사항 상세글 페이지 퍼블리싱

## To Reviewer

모든 상세글 페이지의 디자인을 해당 레이아웃과 동일하게 해도 좋을 지에 대한 의견이 궁금합니다!

## Screenshot

![image](https://github.com/user-attachments/assets/720fd18c-3c7f-4143-9a2e-602267f2a8d5)

2024-12-08 09:48 UTC, gwansikk requested changes

2024-12-08 09:48 UTC, gwansikk commented on apps/community/src/app/api/mock/posts/[id]/route.ts
> +  _request: Request,
👍

2024-12-08 09:48 UTC, gwansikk commented on apps/community/src/app/board/notice/[id]/page.css.ts
> Empty file.

추가한 이유가 있나요

2024-12-08 09:48 UTC, gwansikk commented on apps/community/src/app/board/notice/[id]/page.tsx
> +export const dynamic = 'force-dynamic';
force-dynamic은 임식적으로 TO-DO 주석도 같이 넣어주세요

2024-12-08 09:48 UTC, gwansikk commented on apps/community/src/app/board/notice/[id]/page.tsx
> +  );
```suggestion
  const { data } = await getBoardDetail(postId);
  
  return (
    <Board>
      <Board.Header
        title={data.title}
        author={data.author}
        views={data.views}
        createdAt={data.createdAt}
        file={data.file}
      />
      <Board.Content content={data.content} />
    </Board>
  );
```

2024-12-08 09:48 UTC, gwansikk commented on apps/community/src/app/board/notice/[id]/remote.ts
> +  return response as BaseResponse<BoardDetail>;
```suggestion
  return http.get<BoardDetail>(`${MOCK_END_POINT.NOTICE_DETAIL(id)}`);
```

2024-12-08 09:48 UTC, gwansikk commented on apps/community/src/components/board/board-list.tsx
> +    <Link href={`/board/notice/${data.postId}`}>
하드코딩 된 path 상수로 선언해주세요

2024-12-08 09:48 UTC, gwansikk commented on apps/community/src/components/board/board.tsx
> +}
Content의 `content`는 Render Props 패턴으로 되어 있는데 의도하신 이유가 있나요? `children`이 더 적절해보이는데 특별한 이유가 있는지 궁금합니다.

2024-12-08 09:53 UTC, gwansikk commented
> 모든 상세글 페이지의 디자인을 해당 레이아웃과 동일하게 해도 좋을 지에 대한 의견이 궁금합니다!

일관적인 디자인을 가져가는게 좋다고 생각해요. 일단은. 나중에 다르게 해야할 특별한 요구사항이 있다면 그때 변경하는것으로 해요.

추가로 기존에는 다음글 이전글과 같이 하단에 네비게이터도 있는데요. 해당 페이지는 너무 심플하다고 생각해요. 다른 레퍼런스도 찾아보면서 조금 완성도를 높여보는 건 어떨까요?

<img width="787" alt="image" src="https://github.com/user-attachments/assets/4c3f5d62-7d87-4a6d-90b5-7665dab83b01">

2024-12-08 13:00 UTC, m2na7 commented on apps/community/src/components/board/board.css.ts
> +  gap: '2rem',
```suggestion
  gap: themeVars.spacing.xl,
```

2024-12-08 13:00 UTC, m2na7 commented on apps/community/src/components/board/board.tsx
> +      <h3 className={styles.title}>{title}</h3>
```suggestion
      <h1 className={styles.title}>{title}</h1>
```

2024-12-08 16:04 UTC, SunwooJaeho commented on apps/community/src/app/board/notice/[id]/page.css.ts
미처 확인하지 못한 부분이었어요! 얼른 수정할게요!😆

2024-12-08 16:10 UTC, SunwooJaeho commented on apps/community/src/app/board/notice/[id]/page.tsx
> +export const dynamic = 'force-dynamic';
수정하였어요~~!!

2024-12-08 16:16 UTC, SunwooJaeho commented on apps/community/src/components/board/board.tsx
> +}
header와 통일성 있는 코드를 가져가는 것이 의도였는데, 고민해보니 children이 더 적합할 것 같네요! 바로 수정하겠습니다!👍

2024-12-08 16:23 UTC, SunwooJaeho commented on apps/community/src/components/board/board.tsx
> +}
현재 목데이터로 swagger의 예시 데이터를 사용하고 있는데요, 저도 children이 더 적절하다고 생각하였으나 해당 목데이터의 content가 노드가 아닌 단순 string 값으로 설정되어 있어 render props로 렌더링 중입니다! 혹시 적절한 방법이 있을까요?

2024-12-08 16:24 UTC, SunwooJaeho commented
> > 모든 상세글 페이지의 디자인을 해당 레이아웃과 동일하게 해도 좋을 지에 대한 의견이 궁금합니다!
> 
> 일관적인 디자인을 가져가는게 좋다고 생각해요. 일단은. 나중에 다르게 해야할 특별한 요구사항이 있다면 그때 변경하는것으로 해요.
> 
> 추가로 기존에는 다음글 이전글과 같이 하단에 네비게이터도 있는데요. 해당 페이지는 너무 심플하다고 생각해요. 다른 레퍼런스도 찾아보면서 조금 완성도를 높여보는 건 어떨까요?
> 
> <img alt="image" width="787" src="https://private-user-images.githubusercontent.com/39869096/393584754-4c3f5d62-7d87-4a6d-90b5-7665dab83b01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2NzQwODUsIm5iZiI6MTczMzY3Mzc4NSwicGF0aCI6Ii8zOTg2OTA5Ni8zOTM1ODQ3NTQtNGMzZjVkNjItN2Q4Ny00YTZkLTkwYjUtNzY2NWRhYjgzYjAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDE2MDMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliMjQzYzc3ZGFkZWQ1NWNmNTFmYjU2ZTIzNjExNWQ1YzZjYTFhZmIzYzk2MTJlZWIwNDY5YTkxM2EyOTFhZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.E0Jc8g9Z0lv278HlKFXQ8ij3cRKo0nPrCYGjZx0Ggv0">

적극 동의합니다! 현재 상태에서 추가할 수 있는 기능을 고려해볼게요😊

2024-12-08 16:38 UTC, SunwooJaeho commented on apps/community/src/components/board/board.tsx
> +      <h3 className={styles.title}>{title}</h3>
초기 작업에서 PageHeader를 뒀었는데 삭제한 뒤 미반영했네요, 바로 수정하겠습니다!

2024-12-08 17:06 UTC, SunwooJaeho commented
> > > 모든 상세글 페이지의 디자인을 해당 레이아웃과 동일하게 해도 좋을 지에 대한 의견이 궁금합니다!
> > 
> > 
> > 일관적인 디자인을 가져가는게 좋다고 생각해요. 일단은. 나중에 다르게 해야할 특별한 요구사항이 있다면 그때 변경하는것으로 해요.
> > 추가로 기존에는 다음글 이전글과 같이 하단에 네비게이터도 있는데요. 해당 페이지는 너무 심플하다고 생각해요. 다른 레퍼런스도 찾아보면서 조금 완성도를 높여보는 건 어떨까요?
> > <img alt="image" width="787" src="https://private-user-images.githubusercontent.com/39869096/393584754-4c3f5d62-7d87-4a6d-90b5-7665dab83b01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2NzQwODUsIm5iZiI6MTczMzY3Mzc4NSwicGF0aCI6Ii8zOTg2OTA5Ni8zOTM1ODQ3NTQtNGMzZjVkNjItN2Q4Ny00YTZkLTkwYjUtNzY2NWRhYjgzYjAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDE2MDMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliMjQzYzc3ZGFkZWQ1NWNmNTFmYjU2ZTIzNjExNWQ1YzZjYTFhZmIzYzk2MTJlZWIwNDY5YTkxM2EyOTFhZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.E0Jc8g9Z0lv278HlKFXQ8ij3cRKo0nPrCYGjZx0Ggv0">
> 
> 적극 동의합니다! 현재 상태에서 추가할 수 있는 기능을 고려해볼게요😊

> "목록으로 돌아가기" 버튼을 추가하였어요!

2024-12-09 05:36 UTC, gwansikk commented
@SunwooJaeho 이전글이나 다음글 등 다른 포스트 네이게이터를 추가할 계획은 없나요?

2024-12-09 07:32 UTC, SunwooJaeho commented
> @SunwooJaeho 이전글이나 다음글 등 다른 포스트 네이게이터를 추가할 계획은 없나요?

현재 api 상에서는 이전글과 다음글에 대한 정보를 불러오지 않아 어떤 방식으로 구현하면 좋을 지 고민 중입니다! 따라서 현재는 목록으로 돌아가는 버튼만 추가해두었어요😄

2024-12-09 08:33 UTC, gwansikk approved these changes

2024-12-09 08:34 UTC, merged