feat(community): aside navigation menu 추가
kgu-developers/aics-client pull request #55
Opened 2024-12-13 12:26 UTC by m2na7

## Summary

> #49

aside navigation menu를 추가했습니다.

## Tasks

- aside navigation menu 추가
- AboutLayout 컴포넌트 추가

## To Reviewer

우선적으로 `/app/about` 내에만 Layout 컴포넌트를 추가해주었고, Layout 내에 aside navigation menu를 추가했습니다.
해당방식으로 `/lab`, `/board`, `/member`, `/my` 폴더에 각각 Layout을 잡아줄지,
`/lab`, ` /board`,  `/member,`, `/my` 폴더를 `/(detail)` 폴더를 생성하여 묶은 뒤 Layout을 잡아줄지 의견 부탁드립니다 !

현재는 임시로 about 라우팅에만 사이드바가 적용되어있습니다. (AboutLayout)

## Screenshot

![2024-12-139 21 59-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/cac33192-1832-4724-94e8-b18f56bebc75)

2024-12-16 13:32 UTC, SunwooJaeho commented on apps/community/src/app/about/layout.tsx
> +      </aside>
aside 태그를 분리하신 이유가 궁금해요!

2024-12-17 11:47 UTC, m2na7 commented on apps/community/src/app/about/layout.tsx
> +      </aside>
컴포넌트 내부에서 시맨틱 태그를 활용하는게 더 명확해보이네요~ 수정했습니다 !

2024-12-17 16:47 UTC, gwansikk requested changes
> 해당방식으로 /lab, /board, /member, /my 폴더에 각각 Layout을 잡아줄지

크게 묶는 것보단 지금 처럼 적절한 스코프를 가지는게 좋아보여요. 적절하게 스코프를 나누게 된다면 코드 크기도 줄고 보다 쉽게 관리할 수 있을 거 같아요.

2024-12-17 16:47 UTC, gwansikk commented on apps/community/src/app/about/layout.css.ts
> +  },
디자인 토큰에 없나요? 없다면 선언하여 사용하는게 좋을 거 같아요

2024-12-17 16:47 UTC, gwansikk commented on apps/community/src/constants/pages.ts
해당 상수는 path 상수와 중복되거나 이용할 수 있을 거 같아요. 만약 path 상수가 변경된다면 해당 옵션도 변경해야 하기도 해요. pages 상수를 만드는 것보단, layout에서 아예 path 상수를 넣는 방식은 어떨까요?

2024-12-17 16:47 UTC, gwansikk commented on apps/community/src/components/aside-navigation-menu.tsx
> +        {PATHMAP[page?.id as pathmapKey]}
안전하지 않는 방법으로 보여지는데요 id가 없을 경우 사용하는 fallback이 있었으면 좋을 거 같아요. 정상적인 페이지일 경우 PATHMAP에서 잘 찾겠지만 아닐 경우 에러 페이지라고 생각해요. 상단에서 id를 못찾을 경우 에러 페이지로 넘기거나 렌더링을 안하는 것도 좋은 방법 일거 같아요.

2024-12-18 13:42 UTC, SunwooJaeho commented on apps/community/src/app/about/layout.css.ts
> +  },
현재 min-width만 토큰에 존재하기 때문에 사용한 것으로 보여요!

2024-12-19 01:50 UTC, gwansikk commented on apps/community/src/app/about/layout.css.ts
> +  },
그렇다면 기존에 있는 미디어쿼리 (min-width)를 이용하여 지금 코드의 반대로 작성하면 어떨까요. 해당 코드 처럼 선언하게 된다면 나중에 유지보수하기 어렵다고 생각해요 또한 디자인 토큰을 잡았다면 적절하게 활용하는 게 좋다고 생각해요

2024-12-19 12:14 UTC, m2na7 commented on apps/community/src/app/about/layout.css.ts
> +  },
> 기존에 있는 미디어쿼리 (min-width)를 이용하여 지금 코드의 반대로 작성하면 어떨까요.

@gwansikk 님 의견에 동의하고 해당 방안으로 수정했습니다 !

2024-12-19 12:18 UTC, SunwooJaeho commented
> > 해당방식으로 /lab, /board, /member, /my 폴더에 각각 Layout을 잡아줄지
> 
> 크게 묶는 것보단 지금 처럼 적절한 스코프를 가지는게 좋아보여요. 적절하게 스코프를 나누게 된다면 코드 크기도 줄고 보다 쉽게 관리할 수 있을 거 같아요.

저도 해당 의견에 동의해요! 스코프를 적절하게 나누는 것이 추후 개발에도 더 좋을 것 같아요😄

2024-12-19 12:20 UTC, m2na7 commented on apps/community/src/constants/pages.ts
좋은 방식같아요!
각 Layout 별 독립적인 설정으로, 더욱 관리하기 용이한 방식이라고 생각합니다 👍

2024-12-19 12:22 UTC, SunwooJaeho commented on apps/community/src/app/about/layout.css.ts
> +]);
해당 css를 aside-navigation-menu의 navigationContainer로 옮길 수 있다면 불필요한 div태그 사용을 줄일 수 있을 것 같은데, 어떻게 생각하시나요?

2024-12-19 12:23 UTC, m2na7 commented on apps/community/src/components/aside-navigation-menu.tsx
> +        {PATHMAP[page?.id as pathmapKey]}
기존 `base`(/about)값을 Layout에서 넘겨주고, `base`에 `pathmapKey` 타입을 지정해 줌으로써 해당 문제를 해결했어요 !

2024-12-19 12:36 UTC, m2na7 commented on apps/community/src/app/about/layout.css.ts
> +]);
부모측에서 한 번 더 감싸줘야지 해당 css가 의도대로 작동해요.
layout에서 navigationContainer css코드를 작성하기보다는 aside-navigation-menu에서 작성하는게 맞다고 생각하고, 해당 방식으로 수정했습니다 !

2024-12-19 15:18 UTC, SunwooJaeho approved these changes
LGTM👍👍

2024-12-20 00:48 UTC, gwansikk approved these changes
LGTM

2024-12-20 07:47 UTC, merged